### ISSUE TITLE
Error: undefined method 'epoch' for Time.class

### ISSUE THREAD

**Issue by devlcp** [discordcr/discordcr#202]
Error with code of example.

- Crystal:  0.34.0 [4401e90f0] (2020-04-06)
- OS: Debian 10.3

`
In lib/discordcr/src/discordcr/rest.cr:56:31

 56 | reset_time = Time.epoch(response.headers["X-RateLimit-Reset"].to_u64) # gotta prevent that Y2k38
                        ^----
Error: undefined method 'epoch' for Time.class
`

**Comment by z64** [comment]
This is fixed in master. We should have a release soon to address this and other 0.34 updates.
